hangmanArt={0:( "   ",
                "   ",
                "   ",
                "   ",
                "   "),    
            1:( "___",
                "   ",
                "   ",
                "   ",
                "   "),    
            2:( "___",
                " | ",
                "   ",
                "   ",
                "   "),    
            3:( "___",
                " | ",
                " o ",
                "   ",
                "   "),
            4:( "___",
                " | ",
                " o ",
                " | ",
                "   "),
            5:( "___",
                " | ", 
                " o ",
                "/| ",
                "   "),
            6:( "___",
                " | ", 
                " o ",
                "/|\\",
                "   "),
            7:( "___",
                " | ", 
                " o ",
                "/|\\",
                "/  "),
            8:( "___",
                " | ", 
                " o ",
                "/|\\",
                "/ \\")
            }
words = (
    "apple", "bridge", "carpet", "dragon", "engine", "forest", "glove", "hat", "island", 
    "jacket", "key", "lamp", "mountain", "notebook", "ocean", "pencil", "queen", 
    "river", "sunflower", "train", "umbrella", "village", "window", "xylophone", 
    "yacht", "zebra", "airport", "ball", "camera", "dolphin", "elephant", "flag", 
    "garden", "honey", "insect", "jungle", "kite", "lighthouse", "muscle", "necktie", 
    "orchestra", "penguin", "quilt", "robot", "school", "trophy", "unicorn", 
    "volcano", "whale", "xylophone", "yarn", "zoo", "airplane", "bicycle", "chess", 
    "desk", "engine", "furniture", "glasses", "helmet", "iceberg", "jigsaw", "keyboard", 
    "lemon", "magnifier", "notebook", "oasis", "puzzle", "quasar", "rug", "snowman", 
    "telescope", "umbrella", "vortex", "waterfall", "xenon", "yawn", "zodiac"
)
